name: CI/CD for Food_Ordering_Web

on:
  push:
    paths:
      - 'Food_Ordering_Web/**'
      - 'Food_Ordering_API/**' # Add paths for any dependencies
      - 'Order_API/**'         # Ensures workflow runs if dependencies change
      - 'Restaurant_API/**'
  pull_request:
    paths:
      - 'Food_Ordering_Web/**'
      - 'Food_Ordering_API/**' # Add paths for any dependencies
      - 'Order_API/**'         # Similar for pull requests
      - 'Restaurant_API/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Changed to root of the repository
        file: ./Food_Ordering_Web/Dockerfile
        push: true
        tags: deathbot545/foodorderingweb:latest
        
    - name: Deploy to AWS ECS
      run: |
        aws ecs update-service --cluster Food_Ordering_Web --service Food_Ordering_Web_Services --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-north-1' # Use your AWS region
